// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDszipRK1NXBwoqvihuuuk7soxllMZMX3U',
    appId: '1:711611595943:web:44469a06f9d40846d7af82',
    messagingSenderId: '711611595943',
    projectId: 'spajam-2022-09',
    authDomain: 'spajam-2022-09.firebaseapp.com',
    storageBucket: 'spajam-2022-09.appspot.com',
    measurementId: 'G-0E4C4CGW5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIEdeMEd0a_4NiuXxTWihnZp2DAW1s58M',
    appId: '1:711611595943:android:28014d5f73f0b308d7af82',
    messagingSenderId: '711611595943',
    projectId: 'spajam-2022-09',
    storageBucket: 'spajam-2022-09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7cmHNaXJZ40fyCVvgypSCTnG_ggl5Kqs',
    appId: '1:711611595943:ios:ac030a1e0294b5d8d7af82',
    messagingSenderId: '711611595943',
    projectId: 'spajam-2022-09',
    storageBucket: 'spajam-2022-09.appspot.com',
    iosClientId: '711611595943-rd6l6ot5jnm0er57jq8hvjo291hqhsto.apps.googleusercontent.com',
    iosBundleId: 'com.example.spajamDemoApp',
  );
}
